services:
  telegraphy:
    image: telegraphy:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    env_file: .env
    volumes:
      - /var/lib/telegraphy:/var/lib/telegraphy
