"""init

Revision ID: a0e5f79cb977
Revises: 
Create Date: 2024-12-12 14:55:54.085715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0e5f79cb977'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('short_name', sa.String(length=32), nullable=False),
    sa.Column('author_name', sa.String(length=128), nullable=False),
    sa.Column('author_url', sa.String(length=512), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_token'), 'account', ['token'], unique=True)
    op.create_table('page',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_uri', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('author_name', sa.String(length=128), nullable=False),
    sa.Column('author_url', sa.String(length=512), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1048576), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_page_uri'), 'page', ['page_uri'], unique=True)
    op.create_table('page_view',
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ip', 'user_agent_hash', 'page_id', name='pr__ip__user_agent_hash__page_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_view')
    op.drop_index(op.f('ix_page_page_uri'), table_name='page')
    op.drop_table('page')
    op.drop_index(op.f('ix_account_token'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
